### ISSUE TITLE
why do u use Akka

### ISSUE THREAD

**Issue by HelloTo4x** [alastor1729/starwars#2]
Hi, can u tell me why u choose Akka, why don't you choose project loom for Actor(like light thread), or other Reactive Programming libraries, thank you

**Comment by alastor1729** [comment]
Hi @HelloTo4x, to answer your question (https://github.com/alastor1729/starwars/issues/2#issue-1265697965):

- I initially chose Akka for this project because I wanted to learn more about these Akka concepts (https://github.com/alastor1729/starwars/blob/master/build.sbt#L12-L18) and practice coding with them
- At that time of starting this project (**July 21 2018**), I was not familiar enough with Project Loom or other Reactive Programming libraries.

I hope this answer your question, 🙂

**Comment by HelloTo4x** [comment]
thank u
